# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GDALInit <- function() {
    invisible(.Call('rgdal2_GDALInit', PACKAGE = 'rgdal2'))
}

RGDAL_Open <- function(file, readonly = TRUE, shared = TRUE) {
    .Call('rgdal2_RGDAL_Open', PACKAGE = 'rgdal2', file, readonly, shared)
}

RGDAL_Close <- function(h) {
    invisible(.Call('rgdal2_RGDAL_Close', PACKAGE = 'rgdal2', h))
}

RGDAL_GetDescription <- function(h) {
    .Call('rgdal2_RGDAL_GetDescription', PACKAGE = 'rgdal2', h)
}

RGDAL_GetRasterBand <- function(h, n) {
    .Call('rgdal2_RGDAL_GetRasterBand', PACKAGE = 'rgdal2', h, n)
}

RGDAL_GetRasterXSize <- function(h) {
    .Call('rgdal2_RGDAL_GetRasterXSize', PACKAGE = 'rgdal2', h)
}

RGDAL_GetRasterYSize <- function(h) {
    .Call('rgdal2_RGDAL_GetRasterYSize', PACKAGE = 'rgdal2', h)
}

RGDAL_GetRasterCount <- function(h) {
    .Call('rgdal2_RGDAL_GetRasterCount', PACKAGE = 'rgdal2', h)
}

RGDAL_GetRasterBandXSize <- function(h) {
    .Call('rgdal2_RGDAL_GetRasterBandXSize', PACKAGE = 'rgdal2', h)
}

RGDAL_GetRasterBandYSize <- function(h) {
    .Call('rgdal2_RGDAL_GetRasterBandYSize', PACKAGE = 'rgdal2', h)
}

versionInfo <- function(what = "--version") {
    .Call('rgdal2_versionInfo', PACKAGE = 'rgdal2', what)
}

RGDAL_CleanupAll <- function() {
    invisible(.Call('rgdal2_RGDAL_CleanupAll', PACKAGE = 'rgdal2'))
}

RGDAL_CreateDataset <- function(driver, fname, nrow, ncol, nbands, type, opts) {
    .Call('rgdal2_RGDAL_CreateDataset', PACKAGE = 'rgdal2', driver, fname, nrow, ncol, nbands, type, opts)
}

RGDAL_CreateCopy <- function(h, fname, dname, opts) {
    .Call('rgdal2_RGDAL_CreateCopy', PACKAGE = 'rgdal2', h, fname, dname, opts)
}

RGDAL_GetGeoTransform <- function(h) {
    .Call('rgdal2_RGDAL_GetGeoTransform', PACKAGE = 'rgdal2', h)
}

RGDAL_SetGeoTransform <- function(h, y) {
    .Call('rgdal2_RGDAL_SetGeoTransform', PACKAGE = 'rgdal2', h, y)
}

RGDAL_GetMaskBand <- function(h) {
    .Call('rgdal2_RGDAL_GetMaskBand', PACKAGE = 'rgdal2', h)
}

RGDAL_GetMaskFlags <- function(h) {
    .Call('rgdal2_RGDAL_GetMaskFlags', PACKAGE = 'rgdal2', h)
}

RGDAL_GetBlockSize <- function(h) {
    .Call('rgdal2_RGDAL_GetBlockSize', PACKAGE = 'rgdal2', h)
}

RGDAL_ReadRasterData <- function(h, x, y, xszin, yszin, xszout, yszout, pixsp = 0L, lnsp = 0L) {
    .Call('rgdal2_RGDAL_ReadRasterData', PACKAGE = 'rgdal2', h, x, y, xszin, yszin, xszout, yszout, pixsp, lnsp)
}

RGDAL_writeRasterData <- function(h, raster, x, y, xszout, yszout, pixsp = 0L, lnsp = 0L) {
    .Call('rgdal2_RGDAL_writeRasterData', PACKAGE = 'rgdal2', h, raster, x, y, xszout, yszout, pixsp, lnsp)
}

RGDAL_ReadBlock <- function(h, i, j) {
    .Call('rgdal2_RGDAL_ReadBlock', PACKAGE = 'rgdal2', h, i, j)
}

RGDAL_WriteBlock <- function(h, i, j, blk) {
    .Call('rgdal2_RGDAL_WriteBlock', PACKAGE = 'rgdal2', h, i, j, blk)
}

RGDAL_OGROpen <- function(file, readonly) {
    .Call('rgdal2_RGDAL_OGROpen', PACKAGE = 'rgdal2', file, readonly)
}

RGDAL_ReleaseDataSource <- function(h) {
    invisible(.Call('rgdal2_RGDAL_ReleaseDataSource', PACKAGE = 'rgdal2', h))
}

RGDAL_DS_GetLayerCount <- function(h) {
    .Call('rgdal2_RGDAL_DS_GetLayerCount', PACKAGE = 'rgdal2', h)
}

RGDAL_DS_GetName <- function(h) {
    .Call('rgdal2_RGDAL_DS_GetName', PACKAGE = 'rgdal2', h)
}

RGDAL_DS_GetLayer <- function(h, i) {
    .Call('rgdal2_RGDAL_DS_GetLayer', PACKAGE = 'rgdal2', h, i)
}

RGDAL_GetRasterExtent <- function(h) {
    .Call('rgdal2_RGDAL_GetRasterExtent', PACKAGE = 'rgdal2', h)
}

RGDAL_L_GetName <- function(h) {
    .Call('rgdal2_RGDAL_L_GetName', PACKAGE = 'rgdal2', h)
}

RGDAL_DS_GetLayerByName <- function(h, lnam) {
    .Call('rgdal2_RGDAL_DS_GetLayerByName', PACKAGE = 'rgdal2', h, lnam)
}

RGDAL_GetLayerEnv <- function(h) {
    .Call('rgdal2_RGDAL_GetLayerEnv', PACKAGE = 'rgdal2', h)
}

RGDAL_GetProjectionRef <- function(h) {
    .Call('rgdal2_RGDAL_GetProjectionRef', PACKAGE = 'rgdal2', h)
}

RGDAL_OSRNewSpatialReference <- function(srss) {
    .Call('rgdal2_RGDAL_OSRNewSpatialReference', PACKAGE = 'rgdal2', srss)
}

RGDAL_OSRSetFromUserInput <- function(h, def) {
    .Call('rgdal2_RGDAL_OSRSetFromUserInput', PACKAGE = 'rgdal2', h, def)
}

RGDAL_OSRRelease <- function(h) {
    invisible(.Call('rgdal2_RGDAL_OSRRelease', PACKAGE = 'rgdal2', h))
}

RGDAL_GetWKT <- function(h) {
    .Call('rgdal2_RGDAL_GetWKT', PACKAGE = 'rgdal2', h)
}

RGDAL_GetPROJ4 <- function(h) {
    .Call('rgdal2_RGDAL_GetPROJ4', PACKAGE = 'rgdal2', h)
}

RGDAL_SetProjection <- function(h, proj) {
    .Call('rgdal2_RGDAL_SetProjection', PACKAGE = 'rgdal2', h, proj)
}

RGDAL_L_GetFeatureCount <- function(h) {
    .Call('rgdal2_RGDAL_L_GetFeatureCount', PACKAGE = 'rgdal2', h)
}

RGDAL_L_GetSpatialFilter <- function(h) {
    .Call('rgdal2_RGDAL_L_GetSpatialFilter', PACKAGE = 'rgdal2', h)
}

RGDAL_L_ResetReading <- function(h) {
    invisible(.Call('rgdal2_RGDAL_L_ResetReading', PACKAGE = 'rgdal2', h))
}

RGDAL_L_GetSpatialRef <- function(h) {
    .Call('rgdal2_RGDAL_L_GetSpatialRef', PACKAGE = 'rgdal2', h)
}

RGDAL_G_DestroyGeometry <- function(h) {
    invisible(.Call('rgdal2_RGDAL_G_DestroyGeometry', PACKAGE = 'rgdal2', h))
}

RGDAL_G_AssignSpatialReference <- function(h1, h2) {
    invisible(.Call('rgdal2_RGDAL_G_AssignSpatialReference', PACKAGE = 'rgdal2', h1, h2))
}

RGDAL_G_GetCoordinateDimension <- function(h) {
    .Call('rgdal2_RGDAL_G_GetCoordinateDimension', PACKAGE = 'rgdal2', h)
}

RGDAL_GetPoints <- function(h) {
    .Call('rgdal2_RGDAL_GetPoints', PACKAGE = 'rgdal2', h)
}

RGDAL_GetPointsNested <- function(h) {
    .Call('rgdal2_RGDAL_GetPointsNested', PACKAGE = 'rgdal2', h)
}

RGDAL_DumpGeometry <- function(h, fname) {
    invisible(.Call('rgdal2_RGDAL_DumpGeometry', PACKAGE = 'rgdal2', h, fname))
}

RGDAL_ExecSQL <- function(h, sql) {
    .Call('rgdal2_RGDAL_ExecSQL', PACKAGE = 'rgdal2', h, sql)
}

RGDAL_DS_ReleaseResultSet <- function(h1, h2) {
    invisible(.Call('rgdal2_RGDAL_DS_ReleaseResultSet', PACKAGE = 'rgdal2', h1, h2))
}

RGDAL_GetGeomEnv <- function(h) {
    .Call('rgdal2_RGDAL_GetGeomEnv', PACKAGE = 'rgdal2', h)
}

RGDAL_GetFIDs <- function(h) {
    .Call('rgdal2_RGDAL_GetFIDs', PACKAGE = 'rgdal2', h)
}

RGDAL_GetFeature <- function(h, index) {
    .Call('rgdal2_RGDAL_GetFeature', PACKAGE = 'rgdal2', h, index)
}

RGDAL_F_GetGeometryRef <- function(h) {
    .Call('rgdal2_RGDAL_F_GetGeometryRef', PACKAGE = 'rgdal2', h)
}

RGDAL_G_GetGeometryType <- function(h) {
    .Call('rgdal2_RGDAL_G_GetGeometryType', PACKAGE = 'rgdal2', h)
}

RGDAL_L_GetNextFeature <- function(h) {
    .Call('rgdal2_RGDAL_L_GetNextFeature', PACKAGE = 'rgdal2', h)
}

GetLayerFieldCount <- function(h) {
    .Call('rgdal2_GetLayerFieldCount', PACKAGE = 'rgdal2', h)
}

GetFieldNames <- function(h) {
    .Call('rgdal2_GetFieldNames', PACKAGE = 'rgdal2', h)
}

RGDAL_L_GetFIDColumn <- function(h) {
    .Call('rgdal2_RGDAL_L_GetFIDColumn', PACKAGE = 'rgdal2', h)
}

RGDAL_F_GetFID <- function(h) {
    .Call('rgdal2_RGDAL_F_GetFID', PACKAGE = 'rgdal2', h)
}

RGDAL_L_GetGeometryColumn <- function(h) {
    .Call('rgdal2_RGDAL_L_GetGeometryColumn', PACKAGE = 'rgdal2', h)
}

RGDAL_GetFields <- function(h) {
    .Call('rgdal2_RGDAL_GetFields', PACKAGE = 'rgdal2', h)
}

RGDAL_PrintFeature <- function(h, fname) {
    .Call('rgdal2_RGDAL_PrintFeature', PACKAGE = 'rgdal2', h, fname)
}

RGDAL_GetGeometries <- function(h) {
    .Call('rgdal2_RGDAL_GetGeometries', PACKAGE = 'rgdal2', h)
}

RGDAL_G_CreateGeometry <- function(gtype) {
    .Call('rgdal2_RGDAL_G_CreateGeometry', PACKAGE = 'rgdal2', gtype)
}

RGDAL_DS_TestCapability <- function(h, which) {
    .Call('rgdal2_RGDAL_DS_TestCapability', PACKAGE = 'rgdal2', h, which)
}

RGDAL_L_TestCapability <- function(h, which) {
    .Call('rgdal2_RGDAL_L_TestCapability', PACKAGE = 'rgdal2', h, which)
}

RGDAL_MakeExtent <- function(xmin, xmax, ymin, ymax) {
    .Call('rgdal2_RGDAL_MakeExtent', PACKAGE = 'rgdal2', xmin, xmax, ymin, ymax)
}

RGDAL_G_GetSpatialReference <- function(h) {
    .Call('rgdal2_RGDAL_G_GetSpatialReference', PACKAGE = 'rgdal2', h)
}

RGDAL_OSRClone <- function(h) {
    .Call('rgdal2_RGDAL_OSRClone', PACKAGE = 'rgdal2', h)
}

RGDAL_ApplyGeoTransform <- function(ds, point_list, inverse) {
    .Call('rgdal2_RGDAL_ApplyGeoTransform', PACKAGE = 'rgdal2', ds, point_list, inverse)
}

RGDAL_G_Clone <- function(g) {
    .Call('rgdal2_RGDAL_G_Clone', PACKAGE = 'rgdal2', g)
}

RGDAL_G_TransformTo <- function(g, s) {
    .Call('rgdal2_RGDAL_G_TransformTo', PACKAGE = 'rgdal2', g, s)
}

RGDAL_CopySubset <- function(hRB, xos, yos, xsz, ysz) {
    .Call('rgdal2_RGDAL_CopySubset', PACKAGE = 'rgdal2', hRB, xos, yos, xsz, ysz)
}

RGDALWriteRasterBand <- function(hRB, data, nDSXOff, nDSYOff, nDSXSize, nDSYSize) {
    invisible(.Call('rgdal2_RGDALWriteRasterBand', PACKAGE = 'rgdal2', hRB, data, nDSXOff, nDSYOff, nDSXSize, nDSYSize))
}

RGDAL_G_AddPoint_2D <- function(h, x, y) {
    invisible(.Call('rgdal2_RGDAL_G_AddPoint_2D', PACKAGE = 'rgdal2', h, x, y))
}

RGDAL_G_AddPoint_3D <- function(h, x, y, z) {
    invisible(.Call('rgdal2_RGDAL_G_AddPoint_3D', PACKAGE = 'rgdal2', h, x, y, z))
}

RGDAL_G_Segmentize <- function(h, l) {
    invisible(.Call('rgdal2_RGDAL_G_Segmentize', PACKAGE = 'rgdal2', h, l))
}

RGDAL_G_AddGeometry <- function(h1, h2) {
    .Call('rgdal2_RGDAL_G_AddGeometry', PACKAGE = 'rgdal2', h1, h2)
}

RGDAL_G_CloseRings <- function(h) {
    invisible(.Call('rgdal2_RGDAL_G_CloseRings', PACKAGE = 'rgdal2', h))
}

RGDAL_RasterWarp <- function(h, file, srs, driver, err) {
    .Call('rgdal2_RGDAL_RasterWarp', PACKAGE = 'rgdal2', h, file, srs, driver, err)
}

RGDAL_GetOGRDriverName <- function(h) {
    .Call('rgdal2_RGDAL_GetOGRDriverName', PACKAGE = 'rgdal2', h)
}

RGDAL_GetGDALDriverName <- function(h) {
    .Call('rgdal2_RGDAL_GetGDALDriverName', PACKAGE = 'rgdal2', h)
}

RGDAL_G_Intersects <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Intersects', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Equals <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Equals', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Disjoint <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Disjoint', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Touches <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Touches', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Crosses <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Crosses', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Within <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Within', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Contains <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Contains', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Overlaps <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Overlaps', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Intersection <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Intersection', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Union <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Union', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Difference <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Difference', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_SymDifference <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_SymDifference', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Distance <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Distance', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Centroid <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Centroid', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Boundary <- function(g) {
    .Call('rgdal2_RGDAL_G_Boundary', PACKAGE = 'rgdal2', g)
}

RGDAL_G_ConvexHull <- function(g) {
    .Call('rgdal2_RGDAL_G_ConvexHull', PACKAGE = 'rgdal2', g)
}

RGDAL_G_UnionCascaded <- function(g) {
    .Call('rgdal2_RGDAL_G_UnionCascaded', PACKAGE = 'rgdal2', g)
}

RGDAL_G_Length <- function(g) {
    .Call('rgdal2_RGDAL_G_Length', PACKAGE = 'rgdal2', g)
}

RGDAL_G_Area <- function(g) {
    .Call('rgdal2_RGDAL_G_Area', PACKAGE = 'rgdal2', g)
}

RGDAL_G_Simplify <- function(g, tol) {
    .Call('rgdal2_RGDAL_G_Simplify', PACKAGE = 'rgdal2', g, tol)
}

RGDAL_G_SimplifyPreserveTopology <- function(g, tol) {
    .Call('rgdal2_RGDAL_G_SimplifyPreserveTopology', PACKAGE = 'rgdal2', g, tol)
}

RGDAL_G_Polygonize <- function(g) {
    .Call('rgdal2_RGDAL_G_Polygonize', PACKAGE = 'rgdal2', g)
}

RGDAL_F_Destroy <- function(h) {
    invisible(.Call('rgdal2_RGDAL_F_Destroy', PACKAGE = 'rgdal2', h))
}

RGDAL_G_ForceToMultiPolygon <- function(h) {
    .Call('rgdal2_RGDAL_G_ForceToMultiPolygon', PACKAGE = 'rgdal2', h)
}

RGDAL_IsGeographic <- function(h) {
    .Call('rgdal2_RGDAL_IsGeographic', PACKAGE = 'rgdal2', h)
}

RGDAL_CreateDataSource <- function(driver, name, opts) {
    .Call('rgdal2_RGDAL_CreateDataSource', PACKAGE = 'rgdal2', driver, name, opts)
}

RGDAL_ReadDataset <- function(h, x0, y0, xrin, yrin, xrout, yrout, bands) {
    .Call('rgdal2_RGDAL_ReadDataset', PACKAGE = 'rgdal2', h, x0, y0, xrin, yrin, xrout, yrout, bands)
}

RGDAL_L_SetAttributeFilter <- function(h, query) {
    .Call('rgdal2_RGDAL_L_SetAttributeFilter', PACKAGE = 'rgdal2', h, query)
}

RGDAL_L_SetSpatialFilter <- function(h, g) {
    invisible(.Call('rgdal2_RGDAL_L_SetSpatialFilter', PACKAGE = 'rgdal2', h, g))
}

RGDAL_G_IsEmpty <- function(h) {
    .Call('rgdal2_RGDAL_G_IsEmpty', PACKAGE = 'rgdal2', h)
}

RGDAL_G_IsValid <- function(h) {
    .Call('rgdal2_RGDAL_G_IsValid', PACKAGE = 'rgdal2', h)
}

RGDAL_G_IsSimple <- function(h) {
    .Call('rgdal2_RGDAL_G_IsSimple', PACKAGE = 'rgdal2', h)
}

RGDAL_G_IsRing <- function(h) {
    .Call('rgdal2_RGDAL_G_IsRing', PACKAGE = 'rgdal2', h)
}

RGDAL_G_GetGeometryCount <- function(h) {
    .Call('rgdal2_RGDAL_G_GetGeometryCount', PACKAGE = 'rgdal2', h)
}

RGDAL_G_GetGeometryRef <- function(h, i) {
    .Call('rgdal2_RGDAL_G_GetGeometryRef', PACKAGE = 'rgdal2', h, i)
}

RGDAL_G_Append <- function(g1, g2) {
    .Call('rgdal2_RGDAL_G_Append', PACKAGE = 'rgdal2', g1, g2)
}

RGDAL_G_Buffer <- function(g, dist, n = 30L) {
    .Call('rgdal2_RGDAL_G_Buffer', PACKAGE = 'rgdal2', g, dist, n)
}

RGDAL_GetRasterNoDataValue <- function(h) {
    .Call('rgdal2_RGDAL_GetRasterNoDataValue', PACKAGE = 'rgdal2', h)
}

RGDAL_SetRasterNoDataValue <- function(h, ndv) {
    .Call('rgdal2_RGDAL_SetRasterNoDataValue', PACKAGE = 'rgdal2', h, ndv)
}

RGDAL_GetMetadata <- function(h, domain) {
    .Call('rgdal2_RGDAL_GetMetadata', PACKAGE = 'rgdal2', h, domain)
}

RGDAL_SetMetadata <- function(h, md, domain) {
    .Call('rgdal2_RGDAL_SetMetadata', PACKAGE = 'rgdal2', h, md, domain)
}

RGDAL_DS_CreateLayer <- function(h, lname, srs, geom_type, opts) {
    .Call('rgdal2_RGDAL_DS_CreateLayer', PACKAGE = 'rgdal2', h, lname, srs, geom_type, opts)
}

