# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GDALInit <- function(x = "dummy") {
    .Call('rgdal2_GDALInit', PACKAGE = 'rgdal2', x)
}

GDALOpen <- function(file, readonly = TRUE, shared = TRUE) {
    .Call('rgdal2_GDALOpen', PACKAGE = 'rgdal2', file, readonly, shared)
}

GDALClose <- function(handleXPtr) {
    .Call('rgdal2_GDALClose', PACKAGE = 'rgdal2', handleXPtr)
}

isNullPtr <- function(x) {
    .Call('rgdal2_isNullPtr', PACKAGE = 'rgdal2', x)
}

GDALGetDescription <- function(handleXPtr) {
    .Call('rgdal2_GDALGetDescription', PACKAGE = 'rgdal2', handleXPtr)
}

GDALGetRasterBand <- function(handleXPtr, n) {
    .Call('rgdal2_GDALGetRasterBand', PACKAGE = 'rgdal2', handleXPtr, n)
}

GDALGetRasterBandXSize <- function(handleXPtr) {
    .Call('rgdal2_GDALGetRasterBandXSize', PACKAGE = 'rgdal2', handleXPtr)
}

GDALGetRasterBandYSize <- function(handleXPtr) {
    .Call('rgdal2_GDALGetRasterBandYSize', PACKAGE = 'rgdal2', handleXPtr)
}

